// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCazS8jRs5n-Mja_5Focscuiej2VIShDmQ',
    appId: '1:701008954179:web:b9524b27254a95fe9da5f6',
    messagingSenderId: '701008954179',
    projectId: 'my-social-app-d5cf0',
    authDomain: 'my-social-app-d5cf0.firebaseapp.com',
    storageBucket: 'my-social-app-d5cf0.appspot.com',
    measurementId: 'G-QF83NZ8T21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwlNZuD983qs_icx_UWcj1zJvwolEoH0c',
    appId: '1:701008954179:android:c69ecfde3962f9639da5f6',
    messagingSenderId: '701008954179',
    projectId: 'my-social-app-d5cf0',
    storageBucket: 'my-social-app-d5cf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5St0L4X4-TKRbI3z22MtneSK2SQpuSYU',
    appId: '1:701008954179:ios:0b412d5a76d258d59da5f6',
    messagingSenderId: '701008954179',
    projectId: 'my-social-app-d5cf0',
    storageBucket: 'my-social-app-d5cf0.appspot.com',
    iosBundleId: 'com.example.newSocialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5St0L4X4-TKRbI3z22MtneSK2SQpuSYU',
    appId: '1:701008954179:ios:e34872b2fa4d91a69da5f6',
    messagingSenderId: '701008954179',
    projectId: 'my-social-app-d5cf0',
    storageBucket: 'my-social-app-d5cf0.appspot.com',
    iosBundleId: 'com.example.newSocialApp.RunnerTests',
  );
}
